---
- name: DEPLOY Ansible playbook
  hosts: localhost
  connection: local
  gather_facts: false

  vars:

  vars_files:
  - ../creds/bigip_creds.yml

  tasks:
  - name: DEploy AS3 code
    uri:
      url: https://20.0.58.197:8443/mgmt/shared/appsvcs/declare
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      method: POST
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: false
    register: as3_output

  - name: DEBUG AS3 OUTPUT
    debug:
      msg: "detailed output {{as3_output}}"

...